---
- block:
    
    - name: Directory /root/.ssh
      file:
        path: /root/.ssh
        state: directory
        owner: root
        group: root
        mode: 0700
        recurse: yes
      
    - name: generate SSH key "id_rsa"
      openssh_keypair:
        path: "/root/.ssh/{{ sshkey }}"
        type: rsa
        size: 4096
        state: present
        force: no

    - name: Add ssh-key for root
      authorized_key:
        user: root
        state: present
      #   key: "{{ lookup('file', '/root/.ssh/id_rsa.pub') }}"
      # # when: sshroot is defined
        key: "{{ lookup('file', '{{ item }}') }}"
      with_items:
        - "/root/.ssh/{{ sshkey }}"
  
  when: sshroot|bool

- name: Install ZSH Debian
  apt:
    name: zsh
    state: present
    update_cache: yes
    force_apt_get: yes
  when: ansible_os_family == 'Debian'

- name: Install ZSH RedHat
  yum:
    name: zsh
    state: present
  when: ansible_os_family == 'RedHat'

- name: User creation
  user:
    name: "{{ user }}"
    shell: /bin/bash
    groups: adm
    append: yes

- name: Permit root ssh login
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^PermitRootLogin'
    line: 'PermitRootLogin yes'
  notify:
    - restart sshd

- name: Directory .ssh for user
  file:
    path: /home/{{ user }}/.ssh
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0700
    recurse: yes

- block:
    - name: generate SSH key "id_rsa.pub"
      openssh_keypair:
        path: "/home/{{ user }}/.ssh/{{ sshkey }}"
        type: rsa
        size: 4096
        state: present
        owner: "{{ user }}"
        force: no

    - name: Add ssh-key for user
      authorized_key:
        user: "{{ user }}"
        state: present
        key: "{{ lookup('file', '{{ item }}') }}"
      with_items:
        - "/home/{{ user }}/.ssh/{{ sshkey }}.pub"
  
  tags: auto

- name: Add ssh-key for user
  authorized_key:
    user: "{{ user }}"
    state: present
    key: "/var/lib/jenkins/ansible/files/sshkey/id_rsa_ansible.pub"
  tags: jenk

- name: Copy sudoers file
  template:
    src: sudoers.j2
    dest: /etc/sudoers
    owner: root
    group: root
    mode: 0440

- name: Include distro
  include: "{{ ansible_os_family }}.yml"