---
- name: Directory /root/.ssh
  file:
    path: /root/.ssh
    state: directory
    owner: root
    group: root
    mode: 0700
    recurse: yes
  # when: sshroot is defined
  when: sshroot|bool

- name: Add ssh-key for root
  authorized_key:
    user: root
    state: present
  #   key: "{{ lookup('file', '/root/.ssh/id_rsa.pub') }}"
  # # when: sshroot is defined
    key: "{{ lookup('file', '{{ item }}') }}"
  with_items:
    - "{{ sshkey }}"
  when: sshroot|bool

- name: User creation
  user:
    name: "{{ user }}"
    shell: /bin/bash
    groups: adm
    append: yes

- name: Permit root ssh login
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^PermitRootLogin'
    line: 'PermitRootLogin yes'
  notify:
    - restart sshd

- name: Directory .ssh for user
  file:
    path: /home/{{ user }}/.ssh
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0700
    recurse: yes

- name: Add ssh-key for user
  authorized_key:
    user: "{{ user }}"
    state: present
    key: "{{ lookup('file', '{{ item }}') }}"
  with_items:
    - "{{ sshkey }}"

- name: Copy sudoers file
  template:
    src: sudoers.j2
    dest: /etc/sudoers
    owner: root
    group: root
    mode: 0440

- name: Include distro
  include: "{{ ansible_os_family }}.yml"
