---
- name: User creation
  user:
    name: "{{ user }}"
    shell: /bin/bash
    groups: adm
    append: yes

- name: Directory .ssh for user
  file:
    path: /home/{{ user }}/.ssh
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0700
    recurse: yes

- name: Add ssh-key for user
  authorized_key:
    user: "{{ user }}"
    state: present
    key: "{{ lookup('file', '{{ item }}') }}"
  with_items:
    - "{{ sshkey }}"
