---
- name: EPEL repository
  block:
    - name: Check if EPEL repo was installed
      stat: path={{ epel_repofile_path }}
      register: epel_repofile_result

    - name: Install EPEL repo
      yum:
        name: "{{ epel_repo_url }}"
        state: present
      register: result
      when: not epel_repofile_result.stat.exists

    - name: Import GPG key
      rpm_key:
        key: "{{ epel_repo_gpg_key_url }}"
        state: present
      when: not epel_repofile_result.stat.exists
  when: ansible_distribution != "Fedora"

- name: RedHat basic software
  yum:
    name:
      - make
      - unzip
      - python2-pip
      - wget
      - curl
      - gcc
      - python-pip
      - vim

- name: Install latest passlib with pip
  pip: name=passlib

- name: Deactivate resolv.conf update by NetworkManager
  lineinfile:
    path: /etc/NetworkManager/NetworkManager.conf
    line: dns=none
    create: yes
    insertbefore: '^plugins=ifcfg-rh'

- name: Añadimos DNS
  lineinfile:
    path: /etc/resolv.conf
    line: nameserver {{ dns_network }}
    create: yes